service: funqy-demo

provider:
  name: aws
  runtime: java11
  region: eu-central-1
  endpointType: REGIONAL
  memorySize: 256
  timeout: 15
  deploymentBucket: dasniko-quarkus-demo

functions:
  funqy:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
    package:
      artifact: target/function.zip

package:
  individually: true
